# Use official Node.js image as base
FROM node:14

# Set working directory in the container
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy backend source code
COPY . .

# Expose port
EXPOSE 5000

# Command to run the backend server
CMD ["node", "server.js"]
